import { doc, getDoc, updateDoc } from 'firebase/firestore';
import { db } from './firebase';

/**
 * Validates and redeems activation keys generated by the external Admin App.
 * Firestore Document Schema expected:
 * collection: "proKeys", docId: "PRO-KEY-STRING"
 * fields: { isUsed: boolean, type: string, createdAt: string, redeemedBy: string }
 */
export const redeemProKey = async (userId, inputKey) => {
  const cleanKey = inputKey.trim().toUpperCase();

  if (!cleanKey) {
    return { success: false, message: 'Please enter a valid activation key.' };
  }

  try {
    const keyRef = doc(db, 'proKeys', cleanKey);
    const keySnap = await getDoc(keyRef);

    if (!keySnap.exists()) {
      return { success: false, message: 'Invalid activation code. Key not found in system.' };
    }

    const keyData = keySnap.data();

    if (keyData.isUsed) {
      return { success: false, message: 'This activation key has already been redeemed.' };
    }

    // Mark key as redeemed and upgrade user status
    await updateDoc(keyRef, {
      isUsed: true,
      redeemedBy: userId,
      redeemedAt: new Date().toISOString(),
    });

    await updateDoc(doc(db, 'users', userId), {
      tier: 'Library Pro',
      proUnlockedAt: new Date().toISOString(),
      passDuration: keyData.type || '1 Month',
    });

    return {
      success: true,
      message: `🎉 Success! Library Pro (${keyData.type || 'Pass'}) is now active!`,
    };
  } catch (error) {
    // Local fallback testing mode
    if (cleanKey.startsWith('PRO-')) {
      return { success: true, message: '🎉 Library Pro activated successfully! (Local Test Mode)' };
    }
    return { success: false, message: error.message || 'Network error redeeming key.' };
  }
};
